// See LICENSE for license details.
package example

import chisel3.HasChiselExecutionOptions
import firrtl.{ExecutionOptionsManager, HasFirrtlOptions}
import fpga.cyclonev.TopLevel

/**
  * This provides a way to run the firrtl-interpreter REPL (or shell)
  * on the lowered firrtl generated by your circuit. You will be placed
  * in an interactive shell. This can be very helpful as a debugging
  * technique. Type help to see a list of commands.
  *
  * To run from sbt
  * {{{
  * test:runMain gcd.GCDMMTest
  * }}}
  * To run from sbt and see the half a zillion options try
  * {{{
  * test:runMain gcd.GCDMMTest --help
  * }}}
  */
object BoringAcceleratorBuilder extends App {
  val optionsManager = new ExecutionOptionsManager("chisel3") with HasChiselExecutionOptions with HasFirrtlOptions
  optionsManager.setTargetDirName("quartus/generated")
  optionsManager.setTopName("toplevel_generated")


  chisel3.Driver.execute(optionsManager, () => new TopLevel(new BoringAccelerator))
}
